#!/bin/sh

# Visual Studio Code :: Package list
# code --list-extensions
pkglist=(
amazonwebservices.aws-toolkit-vscode
bung87.vscode-gemfile
CoenraadS.bracket-pair-colorizer
dbaeumer.vscode-eslint
dzhavat.css-flexbox-cheatsheet
eamodio.gitlens
ecmel.vscode-html-css
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
HookyQR.beautify
jrebocho.vscode-random
jsynowiec.vscode-insertdatestring
ms-azuretools.vscode-docker
nathanchapman.JavaScriptSnippets
pnp.polacode
rebornix.ruby
sianglim.slim
steoates.autoimport
streetsidesoftware.code-spell-checker
TabNine.tabnine-vscode
Tyriar.lorem-ipsum
vscode-icons-team.vscode-icons
wingrunr21.vscode-ruby
xabikos.JavaScriptSnippets
xabikos.ReactSnippets
)

for i in ${pkglist[@]}; do
  code --install-extension $i
done
